apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: rigid-db
spec:
  teamId: "rigid"
  volume:
    size: 5Gi
  numberOfInstances: 2
  users:
    rigid:
    - superuser
    - createdb
  databases:
    postgres: rigid
  postgresql:
    version: "12"
    parameters:
      shared_buffers: "64MB"
      max_connections: "50"
      log_statement: "all"
      log_directory: "/var/log/postgresql"
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 768Mi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
      - local all all trust
      - host replication standby all md5
      - host all all all md5
  allowedSourceRanges:
  - 0.0.0.0/0
